<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>HardwareTest.OpenTap.Plugins.Mixins</RootNamespace>
    <Description>Demo OpenTAP mixins for HardwareTest (Annotation)</Description>
    <CreateOpenTapPackage>false</CreateOpenTapPackage>
    <InstallCreatedOpenTapPackage>false</InstallCreatedOpenTapPackage>
    <IsAotCompatible>false</IsAotCompatible>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="OpenTAP" Version="9.32.2" />
  </ItemGroup>
</Project>
