<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>HardwareTest.Authoring.UI.Tests</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsAotCompatible>false</IsAotCompatible>
    <CreateOpenTapPackage>false</CreateOpenTapPackage>
    <InstallCreatedOpenTapPackage>false</InstallCreatedOpenTapPackage>
    <NoWarn>$(NoWarn);xUnit1051</NoWarn>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\HardwareTest.Authoring\HardwareTest.Authoring.csproj" />
    <ProjectReference Include="../HardwareTest.Authoring.ProcessFixture/HardwareTest.Authoring.ProcessFixture.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\plans\opentap\authoring.json;..\..\plans\opentap\sample.TapPlan;..\..\plans\opentap\sample.program.json" Link="fixtures\workspace\%(Filename)%(Extension)" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="OpenTAP" />
    <PackageReference Include="Avalonia.Headless.XUnit" />
    <PackageReference Include="Avalonia.Themes.Fluent" />
    <PackageReference Include="Avalonia.Fonts.Inter" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit.v3" />
    <PackageReference Include="xunit.runner.visualstudio">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>
</Project>
