<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <RootNamespace>HardwareTest.Session.Contracts</RootNamespace>
    <IsPackable>false</IsPackable>
    <IsTestProject>false</IsTestProject>
    <IsAotCompatible>false</IsAotCompatible>
    <NoWarn>$(NoWarn);xUnit1051</NoWarn>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\src\HardwareTest.OpenTap.Host\HardwareTest.OpenTap.Host.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3.assert" Version="3.2.2" />
    <PackageReference Include="xunit.v3.extensibility.core" Version="3.2.2" />
  </ItemGroup>

  <ItemGroup>
    <None Update="IOpenTapSession.approved.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Update="IOpenTapPlanSession.approved.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Update="IOpenTapRunSession.approved.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Update="IOpenTapStationSession.approved.txt" CopyToOutputDirectory="PreserveNewest" />
    <None Update="IOpenTapHostCatalog.approved.txt" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
